"""Add comentariu table

Revision ID: 2cc5d9368a38
Revises: 715dfcfe95f9
Create Date: 2024-04-18 21:05:50.638635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc5d9368a38'
down_revision = '715dfcfe95f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentariu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continut', sa.Text(), nullable=False),
    sa.Column('id_carte', sa.Integer(), nullable=False),
    sa.Column('id_utilizator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carte'], ['carte.id'], ),
    sa.ForeignKeyConstraint(['id_utilizator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentariu')
    # ### end Alembic commands ###
