"""Make user_id nullable in Comentariu

Revision ID: e1a1dcb82c93
Revises: 2cc5d9368a38
Create Date: 2024-04-18 21:14:09.773086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a1dcb82c93'
down_revision = '2cc5d9368a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentariu', schema=None) as batch_op:
        batch_op.alter_column('id_utilizator',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentariu', schema=None) as batch_op:
        batch_op.alter_column('id_utilizator',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
